'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, Check, CheckCircle2, ChevronRight, Clock3, Loader2, ShieldCheck, X, Zap } from 'lucide-react';

type Trace = {
  case: Record<string, any>;
  audits: Array<Record<string, any>>;
  guardrailChecks: Record<string, any>;
  factors: Array<{ factor: string; impact: string; weight: number; description: string }>;
  candidatePlaybooks: Array<{ label: string; playbook: string; score: number; selected: boolean; available: boolean; reason: string }>;
  customerHistory: { segment: string; riskScore: number; retryCount: number; maxRetries: number; pastRecoverySignal: string };
  ledgerEntries: Array<Record<string, any>>;
  proof: { amountAtRisk: number; predictedRecoverable: number; verifiedRecovered: number; verificationSource: string };
  aiDecision: { riskScore: number; recoveryProbability: number; detectedIssue: string; diagnosis: string; selectedAction: string; confidence: string; confidencePercent: number; expectedOutcome: string; decisionFactors: Array<{ factor: string; signal: string; value: number; evidence: string }>; guardrailChecks: Array<{ name: string; status: string; value: string; reason: string }> };
};

const stages = [['DETECT', 'Revenue signal captured'], ['DIAGNOSE', 'Root cause classified'], ['DECIDE', 'Playbook selected'], ['GUARDRAIL', 'Autonomy policy checked'], ['ACT', 'Bounded action executed'], ['VERIFY', 'Settlement confirmed'], ['LEDGER', 'Recovery recorded']] as const;
const money = (value: number) => `₹${Number(value || 0).toLocaleString('en-IN')}`;
const pretty = (value: string) => (value || '').replace(/_/g, ' ');

function stageState(stage: string, trace: Trace) {
  const status = trace.case.status;
  if (stage === 'LEDGER') return trace.ledgerEntries.length ? 'complete' : 'pending';
  if (stage === 'VERIFY') return status === 'RECOVERED' ? 'complete' : status === 'ESCALATED' ? 'blocked' : 'pending';
  if (stage === 'ACT') return trace.case.last_action || status === 'RECOVERED' ? 'complete' : 'pending';
  if (stage === 'GUARDRAIL') return trace.guardrailChecks.overallGuardrailPassed ? 'complete' : 'blocked';
  if (stage === 'DECIDE') return trace.case.playbook ? 'complete' : 'pending';
  if (stage === 'DIAGNOSE') return trace.case.diagnosis_summary ? 'complete' : 'pending';
  return 'complete';
}

export const DecisionTraceModal: React.FC<{ caseId: string | null; onClose: () => void; onRunAction: (id: string, forceApproval?: boolean) => void; isProcessing: boolean }> = ({ caseId, onClose, onRunAction, isProcessing }) => {
  const [trace, setTrace] = useState<Trace | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = useCallback(async () => {
    if (!caseId) return;
    setLoading(true); setError('');
    try { const response = await fetch(`/api/cases/${caseId}/trace`, { cache: 'no-store' }); const json = await response.json(); if (!response.ok) throw new Error(json.error || 'Unable to load case trace'); setTrace(json); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load case trace'); }
    finally { setLoading(false); }
  }, [caseId]);
  useEffect(() => { load(); }, [load]);
  if (!caseId) return null;
  const c = trace?.case;
  const canAct = c && c.status !== 'RECOVERED' && !String(c.status).startsWith('STOPPED');
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-[#02050b]/85 p-3 backdrop-blur-md sm:p-6" onClick={event => event.target === event.currentTarget && onClose()}>
    <section className="mx-auto my-3 max-w-6xl overflow-hidden rounded-3xl border border-[#26374d] bg-[#0b111d]/95 shadow-[0_30px_100px_rgba(0,0,0,.65)] sm:my-8">
      <header className="flex items-start justify-between gap-4 border-b border-[#233149] bg-gradient-to-r from-[#101d31] to-[#0b111d] px-5 py-5 sm:px-8"><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl border border-blue-400/30 bg-blue-400/10 text-blue-300"><Activity /></div><div><p className="text-xs font-mono uppercase tracking-[.22em] text-blue-300">Agent Decision · Case Intelligence</p><h2 className="mt-1 text-xl font-extrabold text-white sm:text-2xl">CASE #{caseId}</h2>{c && <p className="mt-1 text-sm text-slate-400">{c.customer_name} · {pretty(c.playbook)} · {pretty(c.failure_reason)}</p>}</div></div><button onClick={onClose} aria-label="Close case intelligence" className="rounded-xl p-2 text-slate-400 hover:bg-white/5 hover:text-white"><X /></button></header>
      {loading && !c ? <div className="grid min-h-96 place-items-center text-slate-400"><Loader2 className="animate-spin text-blue-400" /></div> : error ? <div className="p-10 text-center text-rose-300">{error}<button onClick={load} className="ml-3 text-blue-300 underline">Retry</button></div> : c && trace && <div className="max-h-[78vh] space-y-7 overflow-y-auto p-5 sm:p-8">
        <div className="grid gap-3 sm:grid-cols-4"><Stat label="Revenue at risk" value={money(c.amount)} tone="yellow" /><Stat label="Risk score" value={`${trace.aiDecision.riskScore} / 100`} tone="red" /><Stat label="Estimated recovery probability" value={`${trace.aiDecision.confidencePercent}% · ${trace.aiDecision.confidence}`} tone="purple" /><Stat label="Verified recovered" value={money(trace.proof.verifiedRecovered)} tone="green" /></div>
        <Panel title="AI Decision" eyebrow="Diagnose → decide"><div className="grid gap-4 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Detected issue</p><p className="mt-1 text-lg font-bold text-purple-200">{trace.aiDecision.detectedIssue}</p><p className="mt-3 text-sm leading-relaxed text-slate-300">{trace.aiDecision.diagnosis}</p></div><div className="rounded-2xl border border-purple-400/30 bg-purple-400/10 p-4 md:min-w-64"><p className="text-xs uppercase tracking-wider text-purple-200">Recommended action</p><p className="mt-2 text-lg font-extrabold text-white">{pretty(trace.aiDecision.selectedAction)}</p><p className="mt-2 text-xs leading-relaxed text-slate-300">{trace.aiDecision.expectedOutcome}</p></div></div></Panel>
        <div className="rounded-2xl border border-[#26374d] bg-[#0e1726] p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-mono uppercase tracking-[.2em] text-blue-300">Decision Trace</p><h3 className="mt-1 text-lg font-bold text-white">Revenue at risk → verified rupee</h3></div><span className="rounded-full border border-blue-400/25 bg-blue-400/10 px-3 py-1 text-xs text-blue-200">Bounded autonomy</span></div><div className="grid gap-3 md:grid-cols-7">{stages.map(([key, label], index) => { const state = stageState(key, trace); return <React.Fragment key={key}><div className={`rounded-xl border p-3 ${state === 'complete' ? 'border-emerald-400/40 bg-emerald-400/10' : state === 'blocked' ? 'border-rose-400/40 bg-rose-400/10' : 'border-slate-700 bg-slate-900/30'}`}><div className="flex items-center justify-between"><span className="text-[11px] font-mono font-bold text-slate-300">0{index + 1}</span>{state === 'complete' ? <Check className="h-4 w-4 text-emerald-300" /> : state === 'blocked' ? <AlertTriangle className="h-4 w-4 text-rose-300" /> : <Clock3 className="h-4 w-4 text-slate-500" />}</div><p className="mt-3 text-xs font-bold uppercase tracking-wider text-white">{key}</p><p className="mt-1 text-xs leading-relaxed text-slate-400">{label}</p></div>{index < stages.length - 1 && <ChevronRight className="hidden self-center text-slate-600 md:block" />}</React.Fragment>; })}</div></div>
        <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-5"><Panel title="Candidate Playbooks" eyebrow="Why this action?"><div className="space-y-2">{trace.candidatePlaybooks.map(candidate => <div key={candidate.label} className={`rounded-xl border p-3 ${candidate.selected ? 'border-purple-400/60 bg-purple-400/10' : 'border-[#26374d] bg-[#101927]'}`}><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{candidate.label}</p><p className="mt-1 text-xs text-slate-400">{candidate.reason || (candidate.available ? 'Supported by the selected recovery playbook.' : 'Unavailable under current case state.')}</p></div><strong className="font-mono text-purple-200">{candidate.score}%</strong>{candidate.selected && <span className="rounded-full bg-purple-400/15 px-2 py-1 text-[10px] font-bold text-purple-200">SELECTED</span>}</div></div>)}</div><div className="mt-4 rounded-xl border border-purple-400/20 bg-purple-400/5 p-4"><p className="text-xs font-bold uppercase tracking-wider text-purple-200">Why did the agent do this?</p><p className="mt-2 text-sm leading-relaxed text-slate-300">{trace.aiDecision.expectedOutcome} {trace.aiDecision.diagnosis}</p></div></Panel><Panel title="Decision factors" eyebrow="Structured explainability"><div className="space-y-3">{trace.aiDecision.decisionFactors.map(factor => <div key={factor.factor} className="rounded-xl border border-[#26374d] bg-[#101927] p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold text-white">{factor.factor}</span><span className={`text-xs font-bold ${factor.signal === 'NEGATIVE' ? 'text-rose-300' : factor.signal === 'POSITIVE' ? 'text-emerald-300' : 'text-slate-400'}`}>{factor.signal}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${factor.signal === 'NEGATIVE' ? 'bg-rose-400' : factor.signal === 'POSITIVE' ? 'bg-emerald-400' : 'bg-slate-500'}`} style={{ width: `${factor.factor === 'Amount threshold' ? Math.min(100, factor.value / 1000) : Math.min(100, Math.max(12, factor.value))}%` }} /></div><p className="mt-1 text-xs leading-relaxed text-slate-400">{factor.evidence}</p></div>)}</div></Panel></div>
          <div className="space-y-5"><Panel title="Guardrails evaluated" eyebrow="Autonomy boundary">{trace.aiDecision.guardrailChecks.map(check => <Guard key={check.name} label={check.name} value={`${check.value} · ${check.reason}`} passed={check.status === 'PASS'} status={check.status} />)}</Panel><Panel title="Customer & payment history" eyebrow="Context used by the agent"><Info label="Customer" value={`${c.customer_name} · ${trace.customerHistory.segment}`} /><Info label="Risk score" value={`${trace.customerHistory.riskScore}/100`} /><Info label="Attempts" value={`${trace.customerHistory.retryCount} of ${trace.customerHistory.maxRetries}`} /><Info label="Failure signal" value={pretty(c.failure_reason)} /><Info label="History signal" value={trace.customerHistory.pastRecoverySignal} /></Panel><Panel title="Settlement proof" eyebrow="Predicted is not recovered"><Info label="Provider / verification" value={trace.proof.verificationSource} /><Info label="Predicted recovery" value={money(trace.proof.predictedRecoverable)} /><Info label="Verified amount" value={money(trace.proof.verifiedRecovered)} /><Info label="Ledger entries" value={String(trace.ledgerEntries.length)} />{trace.ledgerEntries.map(entry => <div key={entry.id} className="mt-3 rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-3 text-xs text-slate-300"><span className="font-mono text-emerald-200">{entry.id}</span><span className="mx-2 text-slate-600">·</span>{money(entry.recovered_amount)} verified {new Date(entry.verified_at).toLocaleString('en-IN')}</div>)}</Panel></div></div>
        <Panel title="Audit trail" eyebrow="Compliance record"><div className="space-y-2">{trace.audits.map(audit => <div key={audit.id} className="grid gap-1 rounded-xl border border-[#26374d] bg-[#101927] p-3 sm:grid-cols-[130px_120px_1fr_auto]"><span className="text-xs font-mono text-slate-500">{new Date(audit.timestamp).toLocaleTimeString('en-IN')}</span><span className="text-xs font-bold text-cyan-200">{pretty(audit.stage)}</span><span className="text-sm text-slate-300">{audit.details}</span><span className="text-xs font-semibold text-emerald-300">{audit.result}</span></div>)}</div></Panel>
      </div>}
      <footer className="flex items-center justify-between gap-3 border-t border-[#233149] bg-[#0a101a] px-5 py-4 sm:px-8"><div className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="h-4 w-4 text-cyan-300" /> Backend trace · settlement-backed ledger</div>{c && canAct && <button onClick={() => onRunAction(c.id, c.status === 'ESCALATED')} disabled={isProcessing} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-500 disabled:opacity-50">{isProcessing ? <Loader2 className="animate-spin" /> : <Zap />} {c.status === 'ESCALATED' ? 'Authorize & execute' : 'Execute recovery'}</button>}</footer>
    </section>
  </div>;
};

function Stat({ label, value, tone }: { label: string; value: string; tone: string }) { const tones: Record<string, string> = { yellow: 'border-amber-400/25 bg-amber-400/5', purple: 'border-purple-400/25 bg-purple-400/5', green: 'border-emerald-400/25 bg-emerald-400/5', red: 'border-rose-400/25 bg-rose-400/5', blue: 'border-blue-400/25 bg-blue-400/5' }; return <div className={`rounded-2xl border p-4 ${tones[tone] || tones.blue}`}><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 truncate text-xl font-extrabold text-white">{value}</p></div>; }
function Panel({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#26374d] bg-[#0e1726] p-4 sm:p-5"><p className="text-[11px] font-mono uppercase tracking-[.18em] text-slate-500">{eyebrow}</p><h3 className="mb-4 mt-1 text-base font-bold text-white">{title}</h3>{children}</section>; }
function Guard({ label, value, passed, status }: { label: string; value: string; passed: boolean; status?: string }) { return <div className="flex items-center gap-3 border-b border-[#26374d] py-3 last:border-0"><div className={`grid h-7 w-7 place-items-center rounded-lg ${passed ? 'bg-emerald-400/15 text-emerald-300' : 'bg-rose-400/15 text-rose-300'}`}>{passed ? <Check /> : <X />}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-white">{label}</p><p className="text-xs text-slate-400">{value}</p></div><span className={`text-xs font-bold ${passed ? 'text-emerald-300' : 'text-rose-300'}`}>{status || (passed ? 'PASS' : 'BLOCK')}</span></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 border-b border-[#26374d] py-2.5 last:border-0"><span className="text-xs text-slate-500">{label}</span><span className="max-w-[65%] text-right text-sm text-slate-200">{value}</span></div>; }
